# Generated by Django 6.0.1 on 2026-01-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientDietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_measure_unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pc', 'Piece'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('cup', 'Cup'), ('oz', 'Ounce')], max_length=10)),
                ('base_quantity', models.FloatField(default=100, help_text='The quantity this nutrition info is based on (100 g, 1 pc, etc.)')),
                ('base_quantity_kcal', models.FloatField(blank=True, null=True)),
                ('base_quantity_protein', models.FloatField(blank=True, null=True)),
                ('base_quantity_carbs', models.FloatField(blank=True, null=True)),
                ('base_quantity_fat', models.FloatField(blank=True, null=True)),
                ('base_quantity_fiber', models.FloatField(blank=True, null=True)),
                ('base_quantity_sugar', models.FloatField(blank=True, null=True)),
                ('base_quantity_salt', models.FloatField(blank=True, null=True)),
                ('base_quantity_cholesterol', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_a', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_c', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_d', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_e', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_k', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_b1', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_b2', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_b3', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_b6', models.FloatField(blank=True, null=True)),
                ('base_quantity_vitamin_b12', models.FloatField(blank=True, null=True)),
                ('base_quantity_folate', models.FloatField(blank=True, null=True)),
                ('base_quantity_calcium', models.FloatField(blank=True, null=True)),
                ('base_quantity_iron', models.FloatField(blank=True, null=True)),
                ('base_quantity_magnesium', models.FloatField(blank=True, null=True)),
                ('base_quantity_potassium', models.FloatField(blank=True, null=True)),
                ('base_quantity_zinc', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(default=1.0, help_text='Quantity in min_measure_unit')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient', to='ingredients.ingredientcategory')),
                ('dietary_tag', models.ManyToManyField(blank=True, related_name='ingredient', to='ingredients.ingredientdietarytag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
