# Generated by Django 6.0.1 on 2026-01-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredient_min_measure_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_calcium',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_carbs',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_cholesterol',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_fat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_fiber',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_folate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_iron',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_kcal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_magnesium',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_potassium',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_protein',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_salt',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_sugar',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_a',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b1',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b12',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b3',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b6',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_c',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_d',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_e',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_k',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_zinc',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
