# Generated by Django 6.0.1 on 2026-01-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_base_quantity_calcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingredients.ingredientmeasurementunit'),
        ),
    ]
