# Generated by Django 6.0.1 on 2026-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredient_default_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pc', 'Piece'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('cup', 'Cup'), ('oz', 'Ounce')], default='g', max_length=10),
        ),
    ]
