# Generated by Django 6.0.1 on 2026-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
