# Generated by Django 6.0.1 on 2026-02-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_alter_ingredientcategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name': 'Ingredient Category', 'verbose_name_plural': 'Ingredient Categories'},
        ),
        migrations.AlterModelOptions(
            name='ingredientdietarytag',
            options={'verbose_name': 'Ingredient Dietary Tag', 'verbose_name_plural': 'Ingredient Dietary Tags'},
        ),
    ]
