# Generated by Django 6.0.1 on 2026-02-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_alter_ingredientcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ingredientdietarytag',
            options={},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='default_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='min_measure_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pc', 'Piece'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('cup', 'Cup'), ('oz', 'Ounce')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=1.0, help_text='Quantity in min_measure_unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity',
            field=models.FloatField(default=100, help_text='The quantity this nutrition info is based on (100 g, 1 pc, etc.)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_folate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_kcal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_magnesium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_salt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_zinc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredientdietarytag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='IngredientMeasurementUnit',
        ),
    ]
