# Generated by Django 6.0.1 on 2026-02-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0011_alter_ingredientcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name': 'Ingredient Category', 'verbose_name_plural': 'Ingredient Categories'},
        ),
        migrations.AlterModelOptions(
            name='ingredientdietarytag',
            options={'verbose_name': 'Ingredient Dietary Tag', 'verbose_name_plural': 'Ingredient Dietary Tags'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='min_measure_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pc', 'Piece'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('cup', 'Cup'), ('oz', 'Ounce')], default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity',
            field=models.FloatField(default=100, help_text='The quantity the NUTRIENTS are based on in default_unit (100 g, 1 pc, etc.)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_calcium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_folate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_iron',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_kcal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_magnesium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_salt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_a',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b12',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_c',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_d',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_e',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_k',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_zinc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientdietarytag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='IngredientMeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pc', 'Piece'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('cup', 'Cup'), ('oz', 'Ounce')], max_length=10)),
                ('conversion_to_base', models.FloatField(help_text='How much of this unit equals the base_quantity')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_units', to='ingredients.ingredient')),
            ],
        ),
    ]
