# Generated by Django 6.0.1 on 2026-02-11 12:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_measurementunit_alter_ingredient_default_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementunit',
            old_name='name',
            new_name='name_plural',
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='name_singular',
            field=models.CharField(default='def_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='MeasurementUnitsConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_unit_quantity', models.FloatField(default=1, validators=[django.core.validators.MinLengthValidator(0.01)])),
                ('second_unit_quantity', models.FloatField(validators=[django.core.validators.MinLengthValidator(0.01)])),
                ('first_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_measurment_unit', to='ingredients.measurementunit')),
                ('second_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_measurment_unit', to='ingredients.measurementunit')),
            ],
        ),
    ]
