# Generated by Django 6.0.1 on 2026-02-13 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0014_rename_name_measurementunit_name_plural_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity',
            field=models.FloatField(default=100, help_text='The quantity the NUTRIENTS are based on in default_unit (100 g, 1 pc, etc.)', validators=[django.core.validators.MinLengthValidator(0.01)]),
        ),
    ]
