# Generated by Django 6.0.1 on 2026-02-15 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_alter_ingredient_base_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity',
            field=models.FloatField(default=100, help_text='The quantity the NUTRIENTS are based on in default_unit (100 g, 1 pc, etc.)', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='measurementunitsconvert',
            name='first_unit_quantity',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='measurementunitsconvert',
            name='second_unit_quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
