# Generated by Django 6.0.1 on 2026-02-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0016_alter_ingredient_base_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
