# Generated by Django 6.0.1 on 2026-02-23 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0017_alter_ingredientcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmeasurementunit',
            name='conversion_to_base',
            field=models.FloatField(help_text='How much of this unit equals the base_quantity', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
