# Generated by Django 6.0.1 on 2026-02-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0018_alter_ingredientmeasurementunit_conversion_to_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementUnitsConvert',
        ),
    ]
