# Generated by Django 6.0.1 on 2026-02-24 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0020_alter_ingredient_base_quantity_calcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity',
            field=models.FloatField(default=100, help_text='The quantity the NUTRIENTS are based on in default_unit (100 g, 1 pc, etc.)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_calcium',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_carbs',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_cholesterol',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_fat',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_fiber',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_folate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_iron',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_kcal',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_magnesium',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_potassium',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_protein',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_salt',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_sugar',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_a',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b1',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b12',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b2',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b3',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_b6',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_c',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_d',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_e',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_vitamin_k',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity_zinc',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='ingredientdietarytag',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientmeasurementunit',
            name='conversion_to_base',
            field=models.FloatField(default=1, help_text='How much of this unit equals the base_quantity', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name_plural',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name_singular',
            field=models.CharField(max_length=40),
        ),
    ]
