# Generated by Django 6.0.3 on 2026-04-06 23:21

import django.db.models.deletion
from django.db import migrations, models

def set_default_units(apps, schema_editor):
    Ingredient = apps.get_model('ingredients', 'Ingredient')
    MeasurementUnit = apps.get_model('ingredients', 'MeasurementUnit')
    gram = MeasurementUnit.objects.filter(code='g').first()
    if gram:
        Ingredient.objects.filter(default_unit__isnull=True).update(default_unit=gram)

class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0022_ingredient_created_at_ingredient_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_units, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='ingredients.measurementunit'),
        ),
    ]
