# Generated by Django 6.0.1 on 2026-03-22 02:17

from django.db import migrations

def add_service_desk(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Service Desk')

def reverse_service_desk(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Service Desk').delete()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_create_groups'),
    ]

    operations = [
        migrations.RunPython(add_service_desk, reverse_service_desk),
    ]
