# Generated by Django 6.0.1 on 2026-01-24 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipecategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient', to='recipes.recipecategory'),
        ),
    ]
