# Generated by Django 6.0.1 on 2026-02-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipeingredient_category_recipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Recipe Category', 'verbose_name_plural': 'Recipe Categories'},
        ),
    ]
