# Generated by Django 6.0.1 on 2026-02-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_measurementunit_alter_ingredient_default_unit_and_more'),
        ('recipes', '0008_alter_recipecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.measurementunit'),
        ),
    ]
