# Generated by Django 6.0.1 on 2026-02-13 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_instructions_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinLengthValidator(0.01)]),
        ),
    ]
