# Generated by Django 6.0.1 on 2026-02-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_alter_ingredient_base_quantity'),
        ('recipes', '0012_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(limit_choices_to=models.Q(('ingredient', models.F('ingredient'))), null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.ingredientmeasurementunit'),
        ),
    ]
