# Generated by Django 6.0.1 on 2026-02-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_alter_ingredientcategory_options_and_more'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='fridge',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fridge',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
