# Generated by Django 6.0.1 on 2026-02-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_measurementunit_alter_ingredient_default_unit_and_more'),
        ('planner', '0003_remove_fridge_user_userfridge_fridge_user_fridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.measurementunit'),
        ),
    ]
