# Generated by Django 6.0.1 on 2026-02-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0016_alter_ingredient_base_quantity_and_more'),
        ('planner', '0004_alter_fridge_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfridge',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfridge',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfridge',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.measurementunit'),
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
    ]
