# Generated by Django 6.0.1 on 2026-02-23 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_usermeallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistgenerationitem',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='userfridge',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='usergrocerylist',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
