# Generated by Django 6.0.1 on 2026-02-24 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_grocerylistgenerationitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistgenerationitem',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='userfridge',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='usergrocerylist',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
