# Generated by Django 6.0.3 on 2026-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_calendarentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbiometrics',
            name='deficit_target',
            field=models.CharField(choices=[('maintain', 'No deficit (maintain)'), ('mild', 'Mild (-250 kcal)'), ('moderate', 'Moderate (-500 kcal)'), ('aggressive', 'Aggressive (-750 kcal)')], default='maintain', max_length=20),
        ),
        migrations.AddField(
            model_name='userbiometrics',
            name='unit_system',
            field=models.CharField(choices=[('metric', 'Metric (kg/cm)'), ('imperial', 'Imperial (lbs/inches)')], default='metric', max_length=10),
        ),
    ]
